name: CI

on:
  push:
    branches:
       [ "master" ]
  pull_request:
    branches:
      [ "master" ]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          script: 
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git pull origin master
